### ISSUE TITLE
Codesandbox example "Changing the animation position" bug

### ISSUE THREAD

**Issue by krisaoe** [nitin42/Animated-Timeline#1]
Hi and thanks, nifty project!
I'm interested in the "Changing the animation position" example, but can't get the [codesandbox](https://codesandbox.io/s/kkjn9jq6k7) to load:
![image](https://user-images.githubusercontent.com/6999809/42937767-5ab284c4-8b93-11e8-9381-18b9ae70fdfa.png)
If you have time to look into it, I'd very much like to see it working.
Cheers

**Comment by nitin42** [comment]
Hey, thanks!

Seems like the codesandbox example you've provided is using `animated-timeline@1.0.0-beta.1` that's why you're getting this error. I'd recommend updating the version. The latest build is `   animated-timeline@1.0.1`

I [updated your example](https://codesandbox.io/s/o75n6omx1y) which is using the latest release, and its working!
